### ISSUE TITLE
vma 7.0.11 build errors

### ISSUE THREAD

**Issue by galuha** [Mellanox/libvma#39]
I am experiencing issues trying to build vma 7.0.11 from source over OFED 3.1_1.0.3 on CentOS 6.7.

Here is the build log:

[log.txt](https://github.com/Mellanox/libvma/files/55415/log.txt)

**Comment by galuha** [comment]
Removing -Werror from configure.ac solves this. I guess it is a gcc 4.4.7 compatibility issue

**Comment by avnerbh** [comment]
Hi,

Thanks for notifying us.
In case you can contribute a patch that doesn't remove -Werror then we'll
gladly integrate it immediately.

However, before that, please make sure that your problem is reproduced when
you checkout a clean source tree of libvma.  Be aware that in Mellanox we
daily compile libvma on RHEL 6.7 as well as on many other platforms that
uses various versions of gcc - newer and older than gcc 4.4.7 (and probably
this specific one too).

Also, please notice that your compilation error in related to a C file that
is actually generated in your environment by flex.  We already encountered
complains about other compilation issue on this file from a user that used
flex 2.5.37 (or 2.5.36) because of a known bug in this particular flex
version - http://sourceforge.net/p/flex/bugs/140/

Feel free to update me about this issue.

Cheers,
  Avner


2015-12-08 14:50 GMT+02:00 galuha <notifications@github.com>:

**Comment by galuha** [comment]
The source tree and base system are perfectly clean. This is a virtual environment with a fresh cent-os / ofed installation. The default flex in CentOS 6.7 repo is buggy 2.5.35. Building flex 2.6.0 required automake 1.15. After succesfull './configure; make install' automake 1.15 didn't show up in the system. I have no intention to struggle with this further if compilation without Werror will not bring me into trouble

**Comment by avnerbh** [comment]
Hi galuha,

We didn't touch the flex file recently; hence, this is probably just a
result of additional compilation checks that we added recently in
Makefiles.  Based on that I believe you can use your local build without
the -Werror flag and you can expect identical behavior as you had before
this issue started.

HTH,
  Avner

2015-12-08 16:27 GMT+02:00 galuha <notifications@github.com>:

**Comment by galuha** [comment]
Thank you

**Comment by avnerbh** [comment]
Hi galuha,

You may want to try VMA-7.0.12.  Among other things it removes the build
errors that disturbed you on CentOS, since from now on VMA is independent
of the user's flex version.
(Hence, the -Werror can left in place with this version)

Please let me know if it works for you.
Cheers,
  Avner

2015-12-11 17:46 GMT+02:00 galuha <notifications@github.com>:

**Comment by galuha** [comment]
7.0.13 still won't build with -Werror on CentOS 6.7

**Comment by avnerbh** [comment]
Hi galuha,

can you please send me the compilation errors/warnings that you get with
7.0.13.

Avner

2016-01-11 17:06 GMT+02:00 galuha <notifications@github.com>:

**Comment by galuha** [comment]
Here
[log.txt](https://github.com/Mellanox/libvma/files/88801/log.txt)

**Comment by avnerbh** [comment]
Thanks.
I now see that the problem is in a yacc file (and not in a lex file as
happen to other user).
I will treat the *.y file same treatment as i did to the *.l file
(processed it using a recent yacc version and add to git the generated
*.c/*h files).

This should solve your problem.  You can check the attached patch file and
i will be glad for your feedback (it might take few days till the patch
will reach github).
Avner

2016-01-13 14:04 GMT+02:00 galuha <notifications@github.com>:

**Comment by avnerbh** [comment]
[vma-yacc.patch.txt](https://github.com/Mellanox/libvma/files/89042/vma-yacc.patch.txt)

**Comment by galuha** [comment]
After the patch application it compiles without errors. Thnx, Avner
